name: Auto Upgrade Deps

on:
  schedule:
    - cron: "0 9 * * *" # run daily at 09:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "Run now (ignore 10-day cadence)?"
        required: false
        default: "false"

permissions:
  contents: write
  pull-requests: write

jobs:
  ncu:
    runs-on: ubuntu-latest

    steps:
      # Gate: only proceed every 10th day (unless forced)
      - name: Gate - run only every 10 days unless forced
        id: gate
        uses: actions/github-script@v7
        env:
          FORCE: ${{ github.event.inputs.force || 'false' }}
        with:
          script: |
            const force = process.env.FORCE === 'true';
            if (force) {
              core.info('Forced run — skipping cadence gate.');
              core.setOutput('skip', 'false');
            } else {
              const days = Math.floor(Date.now() / 86400000); // days since epoch
              const skip = (days % 10 !== 0);
              core.info(`Epoch days=${days} → skip=${skip}`);
              core.setOutput('skip', String(skip));
            }

      - name: Checkout
        if: steps.gate.outputs.skip != 'true'
        uses: actions/checkout@v4

      - name: Setup Node 22
        if: steps.gate.outputs.skip != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install
        if: steps.gate.outputs.skip != 'true'
        run: npm ci

      - name: Upgrade deps (npm-check-updates)
        if: steps.gate.outputs.skip != 'true'
        run: |
          npx npm-check-updates -u         # add --target minor to limit to minor/patch
          npm install

      - name: Lint
        if: steps.gate.outputs.skip != 'true'
        run: npm run lint

      - name: Prettier check
        if: steps.gate.outputs.skip != 'true'
        run: npm run format:check

      - name: Tests
        if: steps.gate.outputs.skip != 'true'
        run: npm test

      - name: Type check
        if: steps.gate.outputs.skip != 'true'
        run: npx tsc --noEmit

      - name: Create PR
        if: steps.gate.outputs.skip != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/deps-${{ github.run_id }}
          commit-message: "chore: upgrade deps via npm-check-updates"
          title: "chore: upgrade dependencies"
          body: |
            Automated dependency update:
            - Ran `npx npm-check-updates -u` and `npm install`
            - Lint, Prettier, tests, and type-check passed.
          labels: dependencies, automated-pr
          signoff: true
          delete-branch: true
